- name: Install wireguard
  become: yes
  package:
    name: wireguard-tools
    state: present

- name: Copy wireguard config
  become: yes
  copy:
    src: "wireguard_conf/{{ wireguard_hostname }}/{{ wireguard_interface }}.conf"
    dest: "/etc/wireguard/{{ wireguard_interface }}.conf"
  notify: Restart wireguard

- name: Add hosts to /etc/hosts
  become: yes
  blockinfile:
    path: /etc/hosts
    block: "{{ lookup('file', 'wireguard_conf/etc_hosts.txt') }}"
    marker: "# {mark} ANSIBLE MANAGED BLOCK wireguard"

- name: Start wireguard
  when: wireguard_enable
  become: yes
  systemd:
    name: "wg-quick@{{ wireguard_interface }}.service"
    enabled: yes
    state: started
  register: wireguard_start
