- name: Restart wireguard
  when: wireguard_enable and (wireguard_start | default({})) is not changed
  become: yes
  systemd:
    name: "wg-quick@{{ wireguard_interface }}.service"
    enabled: yes
    state: restarted
